In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))

x2=np.random.randint(low=1,high=20,size=(50,))

In [3]:
y=3+2*x1-4*x2+np.random.random((50,))

In [4]:
y

array([ -2.40264886,  -8.22076013, -64.99010509,  17.86966976,
       -26.9257298 , -32.94759576, -22.2363392 ,   9.87196075,
       -18.80946295,  -2.6375927 ,  21.67407353, -36.69960338,
        15.35629244,  31.22380645, -24.12738899, -64.26999018,
       -34.2894463 ,  -6.90227105, -52.10305962, -42.08936297,
       -34.60125122,  21.92178569, -12.61124339, -24.17817122,
         1.73483683, -40.11784273,  27.47623947,   5.5972451 ,
       -48.15480018, -10.38538563,  -0.48458298,   9.73043042,
        -6.27861958,  13.20672592, -54.14000276, -44.7335272 ,
         5.63743171, -22.32053431,  11.21165921, -44.68905337,
         5.22323581,  -4.99766046,   1.3573395 ,  -0.06736937,
       -16.78497014, -24.16445512, -16.19151945, -18.38529797,
       -22.64008711,  -0.71294081])

In [5]:
x1

array([ 3, 14,  4, 13,  3,  8, 17,  5,  7, 19, 19, 12, 10, 18, 14,  2,  3,
       19,  6, 11,  3, 17,  6,  4,  5,  6, 18, 17, 10,  9, 14, 11, 19, 19,
        9, 14, 19, 15,  6,  8, 13,  4,  7, 10, 14, 12, 18,  5,  9, 12])

In [6]:
x2

array([ 3, 10, 19,  3,  9, 13, 15,  1,  9, 11,  5, 16,  2,  2, 14, 18, 11,
       12, 17, 17, 11,  4,  7,  9,  3, 14,  3,  8, 18,  8,  8,  4, 12,  7,
       19, 19,  9, 14,  1, 16,  6,  4,  4,  6, 12, 13, 14,  8, 11,  7])

In [7]:
x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

w=np.zeros(x.shape[1]) #initialise B
print(w)

[0. 0. 0.]


In [8]:
x.head()

intercept  x1  x2
0          1   3   3
1          1  14  10
2          1   4  19
3          1  13   3
4          1   3   9

In [9]:
x.shape, w.shape

((50, 3), (3,))

In [18]:
#Calculating predicted y
# Beta * x
def myprediction(features,weights):

    predictions=np.dot(features,weights)
    return(predictions)

myprediction(x,w)
#we get prdicted y values here
#dot product of 50 by 3 to 3 by 1 is 50 by 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
\\#Cal the error 
#yact-y pred

def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)
#error calculation
#yact-ypred
#target=y, features is x values, weights are betas

In [21]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error) #this takes the square of the error
    return(cost)

mycost(y,x,w)


37452.6249522593

In [22]:
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)
    
    return(gradient)

gradient(y,x,w)

array([  712.13912102,  3870.53158804, 11906.5710174 ])

In [44]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights) #weights =weights - learning rate
        weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        if i%100==0:
            print(mycost(target,features,weights),weights)
    return(weights)

my_lr(y,x,0.000001) #0.1 LR gives high step size

37129.52705029867 [-0.00775813 -0.00387053 -0.01190657]
20853.286729153548 [-0.47294116 -0.09660783 -0.87326371]
14936.450652698399 [-0.62491641  0.08240624 -1.38008607]
11161.964572843583 [-0.67241216  0.3218099  -1.74138571]
8398.914058174227 [-0.68371612  0.55656307 -2.02921167]
6331.910603977739 [-0.68136143  0.76874579 -2.2705002 ]
4780.715540555297 [-0.67294891  0.95533965 -2.47703951]
3616.015578459307 [-0.66118382  1.11780012 -2.65528419]
2741.373668705527 [-0.64714704  1.25871303 -2.80960321]
2084.4649723461534 [-0.63136398  1.38074993 -2.94338376]
1591.0048024413595 [-0.6141559   1.48636577 -3.05943099]
1220.244223485169 [-0.5957575   1.57773322 -3.16013311]
941.594443224092 [-0.57635777  1.65674956 -3.24754561]
732.0934647959566 [-0.5561157   1.72506344 -3.32344488]
574.504454979989 [-0.53516741  1.78410483 -3.3893686 ]
455.88826227210296 [-0.51363015  1.83511317 -3.44664854]
366.531856531104 [-0.49160523  1.8791625  -3.49643841]
299.14394588084355 [-0.46918022  1.91718341 -

20.263831764168486 [ 1.78281737  2.07310357 -3.92199801]
20.040723953188717 [ 1.79365128  2.07263728 -3.92251971]
19.820575867926983 [ 1.80441309  2.07217409 -3.92303794]
19.603348244960394 [ 1.81510327  2.07171398 -3.92355271]
19.389002341730695 [ 1.82572232  2.07125694 -3.92406407]
19.177499929634436 [ 1.83627069  2.07080293 -3.92457202]
18.96880328720497 [ 1.84674886  2.07035195 -3.92507658]
18.762875193385018 [ 1.8571573   2.06990397 -3.9255778 ]
18.55967892088797 [ 1.86749647  2.06945897 -3.92607567]
18.359178229647547 [ 1.87776683  2.06901693 -3.92657023]
18.16133736035486 [ 1.88796884  2.06857783 -3.9270615 ]
17.96612102807999 [ 1.89810296  2.06814166 -3.9275495 ]
17.773494415979716 [ 1.90816963  2.06770839 -3.92803426]
17.583423169087425 [ 1.91816931  2.067278   -3.92851578]
17.395873388185883 [ 1.92810243  2.06685048 -3.92899411]
17.21081162376163 [ 1.93796946  2.0664258  -3.92946925]
17.02820487003893 [ 1.94777081  2.06600395 -3.92994122]
16.84802055909362 [ 1.95750694  2.065

5.775915092183646 [ 2.80477337  2.02911839 -3.97120955]
5.745002522531225 [ 2.80880607  2.02894482 -3.97140374]
5.714500035909984 [ 2.81281193  2.0287724  -3.97159664]
5.684402192199769 [ 2.81679112  2.02860114 -3.97178825]
5.654703623448597 [ 2.82074384  2.02843101 -3.97197859]
5.625399032915067 [ 2.82467025  2.02826202 -3.97216766]
5.596483194123927 [ 2.82857053  2.02809415 -3.97235548]
5.567950949933705 [ 2.83244485  2.0279274  -3.97254204]
5.5397972116172305 [ 2.83629339  2.02776176 -3.97272737]
5.512016957953647 [ 2.84011631  2.02759722 -3.97291146]
5.484605234333288 [ 2.8439138   2.02743377 -3.97309432]
5.45755715187373 [ 2.84768601  2.02727142 -3.97327597]
5.4308678865480156 [ 2.85143312  2.02711014 -3.97345641]
5.404532678324249 [ 2.85515529  2.02694994 -3.97363565]
5.378546830316641 [ 2.85885268  2.0267908  -3.97381369]
5.352905707947785 [ 2.86252548  2.02663272 -3.97399055]
5.327604738122091 [ 2.86617382  2.0264757  -3.97416624]
5.302639408410286 [ 2.86979789  2.02631972 -3.9

3.7685504406464836 [ 3.185175    2.01274582 -3.9895275 ]
3.764267367999585 [ 3.18667609  2.01268122 -3.98959979]
3.7600411141623993 [ 3.18816718  2.01261704 -3.98967159]
3.7558709253823728 [ 3.18964836  2.01255329 -3.98974291]
3.7517560579061042 [ 3.19111967  2.01248996 -3.98981376]
3.747695777846772 [ 3.19258119  2.01242706 -3.98988414]
3.743689361053155 [ 3.19403299  2.01236457 -3.98995405]
3.739736092980662 [ 3.19547513  2.0123025  -3.9900235 ]
3.7358352685636937 [ 3.19690766  2.01224085 -3.99009248]
3.73198619209002 [ 3.19833067  2.0121796  -3.990161  ]
3.7281881770765786 [ 3.1997442   2.01211876 -3.99022907]
3.724440546147278 [ 3.20114833  2.01205833 -3.99029669]
3.7207426309119085 [ 3.20254311  2.0119983  -3.99036385]
3.7170937718470514 [ 3.20392861  2.01193866 -3.99043057]
3.713493318178544 [ 3.20530489  2.01187943 -3.99049684]
3.7099406277652442 [ 3.20667201  2.01182059 -3.99056268]
3.706435066984695 [ 3.20803003  2.01176214 -3.99062807]
3.7029760106198317 [ 3.20937901  2.01170

3.4916321482933803 [ 3.32564276  2.00670006 -3.99629162]
3.49102264578301 [ 3.32620902  2.00667569 -3.99631889]
3.490421228871454 [ 3.32677151  2.00665148 -3.99634598]
3.489827790295964 [ 3.32733025  2.00662743 -3.99637288]
3.48924222421677 [ 3.32788528  2.00660354 -3.99639961]
3.4886644261981443 [ 3.32843662  2.00657982 -3.99642616]
3.488094293189734 [ 3.32898428  2.00655624 -3.99645253]
3.4875317235083223 [ 3.32952831  2.00653283 -3.99647873]
3.4869766168195566 [ 3.33006871  2.00650957 -3.99650475]
3.4864288741201515 [ 3.33060551  2.00648647 -3.9965306 ]
3.4858883977201462 [ 3.33113874  2.00646352 -3.99655628]
3.4853550912255313 [ 3.33166843  2.00644072 -3.99658179]
3.4848288595210914 [ 3.33219458  2.00641807 -3.99660712]
3.4843096087533865 [ 3.33271724  2.00639558 -3.99663229]
3.4837972463140012 [ 3.33323642  2.00637323 -3.99665729]
3.4832916808230507 [ 3.33375214  2.00635103 -3.99668213]
3.4827928221129145 [ 3.33426443  2.00632898 -3.99670679]
3.482300581212114 [ 3.33477331  2.0063

3.446642695437731 [ 3.39845834  2.00356607 -3.999798  ]
3.446630018471321 [ 3.39854001  2.00356255 -3.99980194]
3.446617509676272 [ 3.39862113  2.00355906 -3.99980584]
3.4466051668216053 [ 3.39870171  2.00355559 -3.99980972]
3.446592987706035 [ 3.39878176  2.00355215 -3.99981358]
3.446580970157343 [ 3.39886127  2.00354872 -3.99981741]
3.446569112032278 [ 3.39894025  2.00354532 -3.99982121]
3.4465574112159025 [ 3.39901871  2.00354195 -3.99982499]
3.4465458656213603 [ 3.39909665  2.00353859 -3.99982874]
3.4465344731895273 [ 3.39917406  2.00353526 -3.99983247]
3.4465232318885253 [ 3.39925097  2.00353195 -3.99983617]
3.446512139713509 [ 3.39932736  2.00352866 -3.99983985]
3.44650119468615 [ 3.39940324  2.0035254  -3.99984351]
3.446490394854411 [ 3.39947861  2.00352215 -3.99984714]
3.4464797382921684 [ 3.39955349  2.00351893 -3.99985074]
3.4464692230988225 [ 3.39962786  2.00351573 -3.99985432]
3.4464588473989384 [ 3.39970175  2.00351255 -3.99985788]
3.4464486093420783 [ 3.39977514  2.003509

array([ 3.40522234,  2.00327494, -4.00012372])

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
lr=LinearRegression()

In [45]:
x.shape

(50, 3)

In [46]:
lr.fit(x.iloc[:,1:],y) #we are taking all the rows but leaving first col by 1:

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
lr.coef_

array([ 2.00303792, -4.00038891])

In [42]:
lr.intercept_

3.4107293795274565